package mx.axxib.aforedigitalgt.com;

public class Constantes {
	
	public static final String USUARIO_PENSION = "ADIGITAL";
	// Monitor de procesos FOMONIT
	public static final String MONITOR_PROCESOS_PACKAGE = "PKG_CONSULTA_MUNITOR";
	public static final String MONITOR_PROCESOS_OBTIENE_MONITOR = "PRC_RET_OBTIENE_MONITOR";
	public static final String MONITOR_PROCESOS_OBTIENE_JOBS = "PRC_RET_OBTIENE_JOBS";
	public static final String MONITOR_PROCESOS_EJECUTA_JOB = "PRC_RET_EJECUTA_JOB";
	// VER DETALLE CHEQUE FOHISMYD
	public static final String DETALLE_CHEQUE_PACKAGE = "PKG_RET_FUSION_FOHISMYD";
	public static final String CONSULTA_VER_DETALLE_CHEQUE_STORED = "PRC_OBTIENE_CUENTA";
	public static final String SOLICITUD_VER_DETALLE_CHEQUE_STORED = "PRC_SOL_MAT_DESEMPLE";
	public static final String PAGOS_VER_DETALLE_CHEQUE_STORED = "PRC_PAG_EFECTUADOS";
	// VER DETALLE SALDO FOCONCLIC
	public static final String DETALLE_SALDO_PACKAGE = "PKG_RET_FUSION_FOCONCLI";
	public static final String CONSULTA_VER_SALDO_NOMBRE_STORED = "PRC_OBTIENE_DATOS_X_NSS";
	public static final String CONSULTA_VER_SALDO_ID_STORED = "PRC_OBTIENE_DATOS_X_NOMBRE";
	// VER DESMARCA MASIVA FODSMCTA
	public static final String DETALLE_CARGA_MASIVA_PACKAGE = "";
	public static final String DETALLE_CARGA_MASIVA_CREAR_ARCHIVO_STORED = "PRC_GENERA_CARGA";
	public static final String DETALLE_CARGA_MASIVA_REVERSA_ARCHIVO_STORED="PRC_REVERSA_CARGA";
	// VER DESMARCA INDIVIDUAL MASIVA FODSMCTA
	public static final String DETALLE_DESMARCA_MASIVA_PACKAGE = "";
	public static final String DETALLE_DESMARCA_CUENTAS_MASIVAS_STORED = "PRC_DESMARCA_CUENTAS";
	public static final String DETALLE_DESMARCA_MASIVA_INDIVIDUAL_STORED="PRC_DESMARCA_INDIVIDUAL";
	// VER DESMARCA CONSULTAS MARCAS FODSMCTA
	public static final String DETALLE_CONSULTAR_MARCAS_PACKAGE = "";
	public static final String DETALLE_CONSULTAR_MARCAS_CLAVE_STORED = "PRC_CONSULTA_DESMARCA";
	public static final String DETALLE_CONSULTAR_MARCAS_ARCHIVO_STORED="PRC_CONS_DESMARCA_LOTE";
	// VER DESMARCA CONSULTAS MARCAS FOSLDNEG
	public static final String SALDOS_CONSULTAR_IMSS_ISSTE_PACKAGE = "";
	public static final String SALDOS_CARGA_IMSS_STORED = "PRC_CARGA_SALDOS_IMSS";
	public static final String SALDOS_CONSULTAR_IMSS_STORED="PRC_REP_SALDOS_IMSS";
	public static final String SALDOS_CARGA_ISSTE_STORED = "PRC_CARGA_SALDOS_ISSS";
	public static final String SALDOS_CONSULTAR_ISSTE_STORED="PRC_REP_SALDOS_ISSS";
	public static final String SALDOS_VOL_NEGATIVO_STORED = "PRC_REP_SALDOS_VOL";
	// VER DESMARCA CONSULTAS MARCAS FODSMCTA
	public static final String CONSULTAR_TRASPASOS_PACKAGE = "PKG_RET_FUSION_FOMARCTA";
	public static final String CONSULTAR_TRASPASOS_CURP_STORED = "PRC_CONSULTA_CURP";
	public static final String CONSULTAR_TRASPASOS_NSS_STORED = "PRC_CONSULTA_NSS";
	public static final String CONSULTAR_TRASPASOS_STORED = "PRC_OBTIENE_DATOS";
	// VER REPORTE PARCIAL FORPRTPR
	public static final String REPORTE_PARCIAL_PACKAGE = "";
	public static final String REPORTE_PARCIAL_STORED = "PRC_REPORTE_PARCIAL_CONSAR";
	// VER REPORTE PARCIAL FOVALDSM
	public static final String SALARIO_MINIMO_PACKAGE = "PKG_RET_FUSION_FOVALDSM";
	public static final String SALARIO_MINIMO_STORED = "PRC_SALARIO_MIN";
	//VER REPORTE FOREMODE
	public static final String REINVERSION_PROCESO_COMPRAS_VENTAS_PACKAGE = "";
	public static final String REINVERSION_COMPRAS_PROCESO_BOTON_STORED ="PRC_PROCESO_EJECUTAR";
	public static final String REINVERSION_COMPRAS_BOTON_GENERA_REPORTE_STORED = "PRC_REPORTE_COMPRAS";
	public static final String REINVERSION_COMPRAS_BOTON_STORED = "PRC_PROCESO_COMPRAS";
	public static final String REINVERSION_COMPRAS_COMPRA_LOTE_STORED ="FNC_DETALLE_COMPRA";
	public static final String REINVERSION_COMPRAS_VENTAS_BOTON_GENERA_REPORTE_STORED ="PRC_REPORTE_VENTAS";
	public static final String REINVERSION_COMPRAS_VENTAS_BOTON_STORED="PRC_PROCESO_VENTAS";
	public static final String REINVERSION_COMPRAS_VENTAS_LOTE_STORED ="FNC_DETALLE_VENTA";
	//VER REPORTE FOCARSOL
	public static final String CARGA_RETIRO_PARCIAL_PACKAGE ="PKG_RET_FUSION_FOCARSOL";
	public static final String CARGA_RETIRO_PARCIAL_CARGA_ARCHIVO_STORED="PRC_CARGA_ARCHIVO";
	public static final String CARGA_RETIRO_PARCIAL_INICIO_PROCESO_STORED="PRC_INICIO_PROCESO";
	//VER ORDEN DE PAGO FOREPALE
	public static final String ORDEN_PAGO_PACKAGE ="PKG_RET_FUSION_FOREPALE";
	public static final String ORDEN_PAGO_OBTIENE_FECHA_STORED="PRC_OBTIENE_FECHAS";
	public static final String ORDEN_PAGO_REPORTE_ANTERIOR_STORED="PRC_GENERA_REPORTE_ANT";
	public static final String ORDEN_PAGO_CREA_REPORTE_STORED="PRC_REPORTE";
	public static final String ORDEN_PAGO_GENERA_REPORTE_STORED="PRC_GENERA_REPORTE";
	//VER CAPTURA MATRIMONIO DESEMPLEO FOSOREPA
	public static final String CAPTURA_RETIRO_PARCIAL_PACKAGE ="";
	public static final String CAPTURA_RETIRO_PARCIAL_NSS_STORED="PRC_NSS_POST_CHANGE";
	public static final String CAPTURA_RETIRO_PARCIAL_NO_RESOLUCION_STORED="PRC_VALIDA_CAPTURA_DE";
	public static final String CAPTURA_RETIRO_PARCIAL_SIEFORE_STORED="FNC_SALDOS";
	public static final String CAPTURA_RETIRO_PARCIAL_CUENTA_STORED="PRC_VALIDA_CUENTA_RETIRO";
	public static final String CAPTURA_RETIRO_PARCIAL_INVERSION_SALDO_STORED="PRC_VALIDA_COD_TIPO_SALDO";
	//VER CONSULTA RESOLUCION DATA MART FOCODTMR
	public static final String CONSULTA_RESOLUCION_DATA_MART_PACKAGE ="PKG_RET_FUSION_FOCODTMR";
	public static final String CONSULTA_RESOLUCION_DATA_NSS_STORED="PRC_OBTIENE_NOMBRE";
	public static final String CONSULTA_RESOLUCION_DATA_MART_STORED="PRC_DATOS_DATAMART";

}


