package mx.axxib.aforedigitalgt.com;

public class Constantes {
	
	public static final String USUARIO_PENSION = "ADIGITAL";
	// Monitor de procesos FOMONIT
	public static final String MONITOR_PROCESOS_PACKAGE = "PKG_CONSULTA_MUNITOR";
	public static final String MONITOR_PROCESOS_OBTIENE_MONITOR = "PRC_RET_OBTIENE_MONITOR";
	public static final String MONITOR_PROCESOS_OBTIENE_JOBS = "PRC_RET_OBTIENE_JOBS";
	public static final String MONITOR_PROCESOS_EJECUTA_JOB = "PRC_RET_EJECUTA_JOB";
	
	// Modo Desempleo Parcialidad FOCEPARC
	public static final String MOD_DESEMPLEO_PARC_PACKAGE = "PKG_RET_FUSION_FODEPARCE";
	public static final String MOD_DESEMPLEO_PARC_DATOS_SOLICITUD = "PRC_DATOS_SOLICITUD";
	public static final String MOD_DESEMPLEO_PARC_CARGA_PARCIALIDADES = "PRC_CARGA_PARCIALIDADES";
	public static final String MOD_DESEMPLEO_PARC_RETPAR_DETA = "PRC_RETPAR_DETA";
	public static final String MOD_DESEMPLEO_PARC_MARCAS = "PRC_MARCAS";
	public static final String MOD_DESEMPLEO_PARC_LISTA_CANCELACION = "PRC_LISTA_CANCELACION";
	public static final String MOD_DESEMPLEO_PARC_CANCELAR_SOLICITUD = "PRC_CANCELAR_SOLICITUD";
	
	// Venta de titulos por sector de inversión FOVENTIT
	public static final String VENTA_TITULOS_PACKAGE = "PKG_RET_FOVENTIT";
	public static final String VENTA_TITULOS_OBTIENE_MONTO_TOTAL = "PRC_RET_OBTIENE_MONTO_TOTAL";
	public static final String VENTA_TITULOS_OBTENER_TIPO_RETIRO = "PRC_RET_OBTENER_TIPO_RETIRO";
	public static final String VENTA_TITULOS_OBTIENE_MONTO_RETIRO = "PRC_RET_OBTIENE_MONTO_RETIRO";
	public static final String VENTA_TITULOS_OBTIENE_MONTO_CORTE = "PRC_RET_OBTIENE_MONTO_CORTE";
	public static final String VENTA_TITULOS_OBTENER_LOTE_TRASPA = "PRC_RET_OBTENER_LOTE_TRASPA";
	public static final String VENTA_TITULOS_OBTIENE_MONTO_TRASPASOS = "PRC_OBTIENE_MONTO_TRASPASOS";
	public static final String VENTA_TITULOS_OBTENER_RG_DEV_EXCES = "PRC_RET_OBTENER_RG_DEV_EXCES";
	public static final String VENTA_TITULOS_OBTIENE_MONTO_DEV = "PRC_RET_OBTIENE_MONTO_DEV";
	public static final String VENTA_TITULOS_VENTA_TITULOS_MONITOR = "PRC_RET_VENTA_TITULOS_MONITOR";
	public static final String VENTA_TITULOS_VENTA_TITULOS_MONITOR_CT = "PRC_VENTA_TITULOS_MONITOR_CT";
	
	// Notificación de pagos FONOTI16
	public static final String NOTIFICACION_PAGOS_PACKAGE = "PKG_RET_FUSION_FONOTI16";
	public static final String NOTIFICACION_PAGOS_LLENA_INFO = "PRC_LLENA_INFO";
	public static final String NOTIFICACION_PAGOS_ENVIA_FECHA = "PRC_ENVIA_FECHA";
	public static final String NOTIFICACION_PAGOS_EXPORTAR = "PRC_EXPORTAR";
	
		
	
}
